# This file was generated by GoReleaser. DO NOT EDIT.
cask "passbook" do
  version "7.0.4"

  on_macos do
    on_arm do
      sha256 "dc95b147b84eda6714563c4fc3894b2f1015762f2f9d3f377b0cd752ac7f8fae"
      url "https://github.com/mahfuzsust/passbook/releases/download/v#{version}/passbook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca0a714d52dda2d60a53d350fee5d4543450800cfc7fc08e766db0c7d46769f0"
      url "https://github.com/mahfuzsust/passbook/releases/download/v#{version}/passbook_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "passbook"
  desc "Terminal-based password manager built in Go"
  homepage "https://github.com/mahfuzsust/passbook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passbook"

  # No zap stanza required
end
