# This file was generated by GoReleaser. DO NOT EDIT.
cask "passbook" do
  version "7.0.2"

  on_macos do
    on_arm do
      sha256 "dd2f559118aab98da44eb125eeb38be4406af678c6c2d07afad7037f9a116f3b"
      url "https://github.com/mahfuzsust/passbook/releases/download/v#{version}/passbook_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mahfuzsust/passbook"
    end
    on_intel do
      sha256 "13ec813beb67b4f60829fdb58c96b46f45534dbaa2479371d24e6d03c528ea11"
      url "https://github.com/mahfuzsust/passbook/releases/download/v#{version}/passbook_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mahfuzsust/passbook"
    end
  end

  name "passbook"
  desc "Terminal-based password manager built in Go"
  homepage "https://github.com/mahfuzsust/passbook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passbook"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/passbook"]
    end
  end

  # No zap stanza required
end
