# This file was generated by GoReleaser. DO NOT EDIT.
cask "passbook" do
  version "7.0.3"

  on_macos do
    on_arm do
      sha256 "a0c8603ef4ad3a765f63acf314a28043dc57c9381724cd840caea2638189127b"
      url "https://github.com/mahfuzsust/passbook/releases/download/v#{version}/passbook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b57d63295ad286ae0387430d07ced7f59c689e362f50277d3e41aefc0c08c6f"
      url "https://github.com/mahfuzsust/passbook/releases/download/v#{version}/passbook_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "passbook"
  desc "Terminal-based password manager built in Go"
  homepage "https://github.com/mahfuzsust/passbook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passbook"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/passbook"]
    end
  end

  # No zap stanza required
end
