# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passbook < Formula
  desc "Terminal-based password manager built in Go"
  homepage "https://github.com/mahfuzsust/passbook"
  version "3.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.3/passbook_ 3.0.3_ darwin_ amd64.tar.gz"
      sha256 "54b26917e9aa4d32b7d0246def04ddf2daa44d227bc145ca2298accb29bb6807"

      def install
        bin.install "passbook"
      end
    end
    on_arm do
      url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.3/passbook_ 3.0.3_ darwin_ arm64.tar.gz"
      sha256 "b713599fccc7f053d7ade1c465f4af7e827f557f03d0b4e903703dffb0046fc9"

      def install
        bin.install "passbook"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.3/passbook_ 3.0.3_ linux_ amd64.tar.gz"
        sha256 "c33a08b71ffb4973dc9c8b79f7899a10ed309f7498782d365ce55cea936f9bf0"

        def install
          bin.install "passbook"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.3/passbook_ 3.0.3_ linux_ arm64.tar.gz"
        sha256 "a9fe6cc46e57156d16e5b621e000df3a33b4358e156e89e69e2fc30d590dae93"

        def install
          bin.install "passbook"
        end
      end
    end
  end
end
