# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passbook < Formula
  desc "Terminal-based password manager built in Go"
  homepage "https://github.com/mahfuzsust/passbook"
  version "3.0.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.9/passbook_3.0.9_darwin_amd64.tar.gz"
      sha256 "12a69cda3814c3838412dad9198642ed7fa718d4bf7a37581a38c73d5fa5520a"

      def install
        bin.install "passbook"
      end
    end
    on_arm do
      url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.9/passbook_3.0.9_darwin_arm64.tar.gz"
      sha256 "57025da7b074e2b901037da4824f409079ea290b957e68b07acd815efaff35cd"

      def install
        bin.install "passbook"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.9/passbook_3.0.9_linux_amd64.tar.gz"
        sha256 "6db0860de0d59bdf831024e88a39d58395bb2fd11e9286cba0b6e2f39e5fe901"

        def install
          bin.install "passbook"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mahfuzsust/passbook/releases/download/v3.0.9/passbook_3.0.9_linux_arm64.tar.gz"
        sha256 "f36c9ae7b7c5fe125e688eac5a6c1f5d1ff8fc4f5f0c9e7efb298af19f1dbd52"

        def install
          bin.install "passbook"
        end
      end
    end
  end

  test do
    system "#{bin}/passbook", "--help"
  end
end
