# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passbook < Formula
  desc "Terminal-based password manager built in Go"
  homepage "https://github.com/mahfuzsust/passbook"
  version "4.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mahfuzsust/passbook/releases/download/v4.0.0/passbook_4.0.0_darwin_amd64.tar.gz"
      sha256 "575c988b35766675a945feb5bd9645791682072fb25261fd9b91bbb5a4f30e2f"

      def install
        bin.install "passbook"
      end
    end
    on_arm do
      url "https://github.com/mahfuzsust/passbook/releases/download/v4.0.0/passbook_4.0.0_darwin_arm64.tar.gz"
      sha256 "742faa6c5d1b94b5d6ef5973ef0b38028a61cdc7f7c39fd815cdd00e77f5c430"

      def install
        bin.install "passbook"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mahfuzsust/passbook/releases/download/v4.0.0/passbook_4.0.0_linux_amd64.tar.gz"
        sha256 "73d2ffce29fa50caf0b498c016903dc38cd184284f528d6087882647d0ddd4c8"

        def install
          bin.install "passbook"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mahfuzsust/passbook/releases/download/v4.0.0/passbook_4.0.0_linux_arm64.tar.gz"
        sha256 "dbf156f6f83181951b9e1c78b6dbf6fae45d84d8efced7da48825be71501034b"

        def install
          bin.install "passbook"
        end
      end
    end
  end

  test do
    system "#{bin}/passbook", "--help"
  end
end
